/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedServersRouteImport } from './routes/_authenticated/servers'
import { Route as AuthenticatedNodesRouteImport } from './routes/_authenticated/nodes'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminSettingsRouteImport } from './routes/_authenticated/_admin/admin.settings'
import { Route as AuthenticatedAdminAdminEggsRouteImport } from './routes/_authenticated/_admin/admin.eggs'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServersRoute = AuthenticatedServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNodesRoute = AuthenticatedNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminSettingsRoute =
  AuthenticatedAdminAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminEggsRoute =
  AuthenticatedAdminAdminEggsRouteImport.update({
    id: '/admin/eggs',
    path: '/admin/eggs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/nodes': typeof AuthenticatedNodesRoute
  '/servers': typeof AuthenticatedServersRoute
  '/admin/eggs': typeof AuthenticatedAdminAdminEggsRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/nodes': typeof AuthenticatedNodesRoute
  '/servers': typeof AuthenticatedServersRoute
  '/admin/eggs': typeof AuthenticatedAdminAdminEggsRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/console': typeof AuthenticatedConsoleRoute
  '/_authenticated/nodes': typeof AuthenticatedNodesRoute
  '/_authenticated/servers': typeof AuthenticatedServersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_admin/admin/eggs': typeof AuthenticatedAdminAdminEggsRoute
  '/_authenticated/_admin/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/console'
    | '/nodes'
    | '/servers'
    | '/admin/eggs'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/console'
    | '/nodes'
    | '/servers'
    | '/admin/eggs'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/_admin'
    | '/_authenticated/console'
    | '/_authenticated/nodes'
    | '/_authenticated/servers'
    | '/_authenticated/'
    | '/_authenticated/_admin/admin/eggs'
    | '/_authenticated/_admin/admin/settings'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers': {
      id: '/_authenticated/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AuthenticatedServersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nodes': {
      id: '/_authenticated/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof AuthenticatedNodesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/settings': {
      id: '/_authenticated/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/eggs': {
      id: '/_authenticated/_admin/admin/eggs'
      path: '/admin/eggs'
      fullPath: '/admin/eggs'
      preLoaderRoute: typeof AuthenticatedAdminAdminEggsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminEggsRoute: typeof AuthenticatedAdminAdminEggsRoute
  AuthenticatedAdminAdminSettingsRoute: typeof AuthenticatedAdminAdminSettingsRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminEggsRoute: AuthenticatedAdminAdminEggsRoute,
  AuthenticatedAdminAdminSettingsRoute: AuthenticatedAdminAdminSettingsRoute,
  AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRoute
  AuthenticatedNodesRoute: typeof AuthenticatedNodesRoute
  AuthenticatedServersRoute: typeof AuthenticatedServersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedConsoleRoute: AuthenticatedConsoleRoute,
  AuthenticatedNodesRoute: AuthenticatedNodesRoute,
  AuthenticatedServersRoute: AuthenticatedServersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
